# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cc4e4bf1c86bab2253975e5dde48f4f42301c023d19e80d2b417b1b1e4f81b8633d973781821701057be20941b4210ad0b457d61d41ed67956d73f77f20cfc55

test:
  secret_key_base: 6306bf3ad396b39135e324b63a7f2cf3fb596362a1577dc11a6c8434496cdf7874bd063ba40be257bc91355338020e18b9ded2510f8e8cde262a15cf8cad3bab

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
